base: ghcr.io/vanilla-os/pico:main
name: Vanilla VSO
id: vanilla-vso
labels:
  maintainer: Vanilla OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
  - echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends

modules:
  - name: systemd
    type: apt
    source:
      packages:
        - systemd
        - libpam-systemd

  - name: distrobox-init-pkgs
    type: apt
    source:
      packages:
        - apt-utils
        - bash-completion
        - bc
        - bzip2
        - curl
        - dialog
        - diffutils
        - findutils
        - iproute2
        - gnupg
        - gnupg2
        - gpgsm
        - libkrb5-3
        - libcap2-bin
        - hostname
        - iputils-ping
        - less
        - keyutils
        - libnss-mdns
        - libnss-myhostname
        - libvte-2.9*-common
        - libvte-common
        - locales
        - locales-all
        - man-db
        - manpages
        - mtr
        - lsof
        - ncurses-base
        - passwd
        - pinentry-curses
        - openssh-client
        - procps
        - sudo
        - pigz
        - time
        - rsync
        - tzdata
        - util-linux
        - wget
        - unzip
        - zip
        - xauth
        - tree
        - tcpdump
        - traceroute
        - xz-utils
        - libgl1
        - libegl1-mesa
        - libgl1-mesa-glx
        - libegl1
        - libglx-mesa0
        - libvulkan1
        - mesa-vulkan-drivers

  - name: vanilla-tools
    type: shell
    source:
      type: tar
      # switch to production build once in production
      url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/continuous/vanilla-tools.tar.gz
    commands:
    - mkdir -p /usr/bin
    - cp /sources/vanilla-tools/nrun /usr/bin/nrun
    - chmod +x /usr/bin/nrun
    - cp /sources/vanilla-tools/cur-gpu /usr/bin/cur-gpu
    - chmod +x /usr/bin/cur-gpu

  - name: host-aliases
    type: shell
    commands:
      - ln -s /usr/bin/host-spawn /usr/bin/vso
      - ln -s /usr/bin/host-spawn /usr/bin/apx
      - ln -s /usr/bin/host-spawn /usr/bin/ikaros
      - ln -s /usr/bin/host-spawn /usr/bin/vanilla-sideload
      - sh /usr/share/apx/distrobox/gen-distrobox-links
      - chmod +x /usr/bin/os-shell
      - chmod +x /usr/bin/abroot

  - name: cleanup
    type: shell
    commands:
      - apt autoremove -y
      - apt clean

  - name: enable-apt-hooks
    type: shell
    commands:
      - mv /etc/apt/___apt.conf.d/ /etc/apt/apt.conf.d/
