#!/bin/bash

package="$(cat /tmp/vso-transaction)"
log_file="/tmp/vso-export-log.log"

if [ -n "$SUDO_USER" ]; then
  username=$SUDO_USER
else
  echo "VSO does not work with root privileges, no programs will be exported. Use 'vso export -a $package' to manually export it."
fi

su -c "/usr/bin/vso export -a $package" $username >> "$log_file" 2>&1

if [ $? -ne 0 ]; then
  echo "Error occurred while exporting. Check $log_file for details."
  echo "No programs will be exported. Use 'vso export -a $package' to manually export it."
fi